### ISSUE TITLE
pos_tag(syllable_tokenize(sentence, 'kor'), lang='kor')가 작동하지 않습니다.

### ISSUE THREAD

**Issue by ghost** [cwnu-airlab/NLTKo#1]
syllable_tokenize(sentence, 'kor')을 하면 음절토크나이징이 되고 나서 음절의 리스트로 리턴이 되어서 이것을 가지고 pos_tag을 하려면 sentence_tokenzize의 함수 안에 인풋으로 음절이 합쳐져서 str으로 들어가야 하는데 음절의 리스트가 들어가서 작동이 되질 않고 있습니다.
제가 사용한 환경은 ubuntu 20.04에 conda 환경에서 테스트를 진행하였습니다. 테스트에 쓰인 패키지 리스트로 업로드하였습니다.
[packagelist.txt](https://github.com/cwnu-airlab/NLTKo/files/9915423/packagelist.txt)

**Comment by kamuichan80** [comment]
> syllable_tokenize(sentence, 'kor')을 하면 음절토크나이징이 되고 나서 음절의 리스트로 리턴이 되어서 이것을 가지고 pos_tag을 하려면 sentence_tokenzize의 함수 안에 인풋으로 음절이 합쳐져서 str으로 들어가야 하는데 음절의 리스트가 들어가서 작동이 되질 않고 있습니다. 제가 사용한 환경은 ubuntu 20.04에 conda 환경에서 테스트를 진행하였습니다. 테스트에 쓰인 패키지 리스트로 업로드하였습니다. [packagelist.txt](https://github.com/cwnu-airlab/NLTKo/files/9915423/packagelist.txt)

pos_tag함수를 적용할 때는 syllable_tokenize을 적용하지 않고 pos_tag(sentence, lang='kor')을 적용하면 예제에 나와있는 결과와 동일하게 나왔습니다.
